# Generated by Django 3.0.8 on 2020-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_remove_zone_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregat',
            name='n_zone',
            field=models.IntegerField(),
        ),
    ]
