# Generated by Django 3.0.8 on 2020-07-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_pizza_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
