# Generated by Django 3.0.8 on 2020-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20200724_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZonPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(to='app_one.CorpProducts')),
            ],
        ),
        migrations.CreateModel(
            name='AgrDom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zon', models.ManyToManyField(to='app_one.ZonPizza')),
            ],
        ),
    ]
