# Generated by Django 3.0.8 on 2020-07-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_agrdom_corpproducts_zonpizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrdom',
            name='zon',
        ),
        migrations.AddField(
            model_name='agrdom',
            name='one',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_one.ZonPizza'),
            preserve_default=False,
        ),
    ]
