# Generated by Django 3.0.8 on 2020-07-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_auto_20200724_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonpizza',
            name='products',
        ),
        migrations.DeleteModel(
            name='AgrDom',
        ),
        migrations.DeleteModel(
            name='CorpProducts',
        ),
        migrations.DeleteModel(
            name='ZonPizza',
        ),
    ]
