# Generated by Django 3.0.8 on 2020-07-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0008_auto_20200724_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='corpus',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_one.Corpus'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Agregat',
        ),
    ]
