# Generated by Django 3.0.8 on 2020-07-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0009_auto_20200724_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_zag', models.CharField(blank=True, max_length=40, verbose_name='гос номер')),
                ('n_agr', models.IntegerField(verbose_name='номер агрегата')),
                ('n_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.Zone')),
            ],
        ),
    ]
