# Generated by Django 3.0.8 on 2020-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0010_agregat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='name_corpus',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='n_zone',
            field=models.IntegerField(unique=True, verbose_name='номер зони'),
        ),
    ]
