# Generated by Django 3.0.8 on 2020-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0014_delete_agregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAgregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_controller', models.IntegerField(blank=True, null=True)),
                ('t_delta', models.IntegerField(blank=True, null=True)),
                ('t_input', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('t_output', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('auto_hand', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('capacity_warm', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('capacity_current', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('digital_input', models.IntegerField(blank=True, null=True)),
                ('digital_output', models.IntegerField(blank=True, null=True)),
                ('parameters', models.IntegerField(blank=True, null=True)),
                ('w_accumulate', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('w_current', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True)),
                ('zdate', models.DateField(blank=True, null=True)),
                ('ztime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_agregate',
                'managed': False,
            },
        ),
    ]
