# Generated by Django 3.0.8 on 2020-08-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0017_auto_20200806_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maagregate',
            options={},
        ),
    ]
